/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Intro = {
  _id: string;
  _type: 'intro';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  jobTitle: string;
  name: string;
  email?: {
    label?: string;
    value?: string;
  };
  github?: {
    label?: string;
    value?: string;
  };
  linkedIn?: {
    label?: string;
    value?: string;
  };
  resume: {
    label?: string;
    value?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
      };
      media?: unknown;
      _type: 'file';
    };
  };
  about: string;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  maintenanceMode: boolean;
  comingSoonHeading: string;
  comingSoonMessage: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | Slug
  | Intro
  | SanityFileAsset
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Settings;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../src/queries/indexSettings.ts
// Variable: INDEX_SETTINGS_QUERY
// Query: *[_type == "settings"][0] {  _id,  maintenanceMode,  comingSoonHeading,  comingSoonMessage}
export type INDEX_SETTINGS_QUERYResult = {
  _id: string;
  maintenanceMode: boolean;
  comingSoonHeading: string;
  comingSoonMessage: string;
} | null;

// Source: ../src/queries/intro.ts
// Variable: INTRO_QUERY
// Query: *[_id == "intro"][0] {  _id,  image {    asset -> {      ...    }  },  jobTitle,  name,  email {    label,    value  },  github {    label,    value  },  linkedIn {    label,    value  },  resume {    label,    value {      asset -> {        ...      }    }  },  about}
export type INTRO_QUERYResult =
  | {
      _id: string;
      image: null;
      jobTitle: null;
      name: null;
      email: null;
      github: null;
      linkedIn: null;
      resume: null;
      about: null;
    }
  | {
      _id: string;
      image: {
        asset: {
          _id: string;
          _type: 'sanity.imageAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      };
      jobTitle: string;
      name: string;
      email: {
        label: string | null;
        value: string | null;
      } | null;
      github: {
        label: string | null;
        value: string | null;
      } | null;
      linkedIn: {
        label: string | null;
        value: string | null;
      } | null;
      resume: {
        label: string | null;
        value: {
          asset: {
            _id: string;
            _type: 'sanity.fileAsset';
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            source?: SanityAssetSourceData;
          } | null;
        } | null;
      };
      about: string;
    }
  | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n*[_type == "settings"][0] {\n  _id,\n  maintenanceMode,\n  comingSoonHeading,\n  comingSoonMessage\n}\n': INDEX_SETTINGS_QUERYResult;
    '\n*[_id == "intro"][0] {\n  _id,\n  image {\n    asset -> {\n      ...\n    }\n  },\n  jobTitle,\n  name,\n  email {\n    label,\n    value\n  },\n  github {\n    label,\n    value\n  },\n  linkedIn {\n    label,\n    value\n  },\n  resume {\n    label,\n    value {\n      asset -> {\n        ...\n      }\n    }\n  },\n  about\n}\n': INTRO_QUERYResult;
  }
}
